### ISSUE TITLE
Question about residency management.

### ISSUE THREAD

**Issue by kingofthebongo2008** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#8]
Hello,
How do you recommend using this library with residency management.
Microsoft has an example about this.
Do you have any recommendations about this?
Thank you

**Comment by adam-sawicki-a** [comment]
We recommend not to use `Evict`/`MakeResident`, and so the library doesn't support it. Eviction works on the level of whole memory blocks (Heap or a committed Resource). So if you want any of your resources (e.g. the bigger ones) to be managed by Microsoft's D3D12Residency library or evicted manually, you must allocate them as committed. Which you can do still using D3D12MA - you just need to add `ALLOCATION_FLAG_COMMITTED`. The other resources that you don't want to evict (e.g. the critically important ones like render targets, the small ones that are better created as placed so their allocation doesn't take too much time) can be created normally using D3D12MA.

**Comment by kingofthebongo2008** [comment]
Thank you. 
This helps.

**Comment by jeffdr** [comment]
Adam,

I'm wondering a bit if you could elaborate on why use of Evict/MakeResident isn't recommended. Are there reasons apart from complicating the D3D12MA library?

Thanks!

**Comment by adam-sawicki-a** [comment]
There is nothing wrong with using Evict/MakeResident. Many games/programs use them together with D3D12MA. But as I said before, residency management works on a level of entire memory blocks, so it contradicts the purpose of this library, which is to suballocate resources out of larger heaps.

Do you have some proposal how support for Evict/MakeResident could be added to the library API? I think that calling native D3D12 functions on resources or heaps managed by D3D12MA is good enough.

**Comment by jeffdr** [comment]
Thanks, that makes sense. And no, I don't really have a proposal for the library, since managing heap residency does kind of contradict the purpose of the library. The only schemes I could think of would be something along the lines of creating resources into numerical "categories" such that a given heap only has resources of a given category, and then exposing some kind of iterator over heaps to allow users to evict them as desired. But I wouldn't really advocate for this addition as I'm not sure it would be generally useful enough to be worth it.

For my team's purposes, we'll focus on managing residency of committed resources only, as you suggest.

**Comment by adam-sawicki-a** [comment]
I once seen a solution applied in some AAA game that they were creating all small resources (e.g. <= 256 KB of estimated size) inside larger heaps and everything bigger, as well as all render target, depth-strencil and UAV as committed. The committed ones were managed by Microsoft's D3D12Residency library. Small ones were always resident. The RT/DS/UAV ones were assigned high residency priority.
